/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.tables.Countries;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountryRecord extends UpdatableRecordImpl<CountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.countries.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.countries.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.countries.created_at_</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.countries.created_at_</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.countries.updated_at_</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.countries.updated_at_</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.countries.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.countries.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.countries.name_</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.countries.name_</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.countries.code_</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.countries.code_</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.countries.currency_</code>.
     */
    public void setCurrency(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.countries.currency_</code>.
     */
    public String getCurrency() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryRecord
     */
    public CountryRecord() {
        super(Countries.COUNTRIES);
    }

    /**
     * Create a detached, initialised CountryRecord
     */
    public CountryRecord(Long id_, OffsetDateTime createdAt_, OffsetDateTime updatedAt_, Boolean removed_, String name_, String code_, String currency_) {
        super(Countries.COUNTRIES);

        setId(id_);
        setCreatedAt(createdAt_);
        setUpdatedAt(updatedAt_);
        setRemoved(removed_);
        setName(name_);
        setCode(code_);
        setCurrency(currency_);
        resetTouchedOnNotNull();
    }
}
