/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.tables.Files;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.files.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.files.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.files.created_at_</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.files.created_at_</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.files.updated_at_</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.files.updated_at_</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.files.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.files.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.files.name_</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.files.name_</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.files.url_path_</code>.
     */
    public void setUrlPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.files.url_path_</code>.
     */
    public String getUrlPath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.files.type_</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.files.type_</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.files.size_</code>.
     */
    public void setSize(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.files.size_</code>.
     */
    public Long getSize() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(Files.FILES);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id_, OffsetDateTime createdAt_, OffsetDateTime updatedAt_, Boolean removed_, String name_, String urlPath_, String type_, Long size_) {
        super(Files.FILES);

        setId(id_);
        setCreatedAt(createdAt_);
        setUpdatedAt(updatedAt_);
        setRemoved(removed_);
        setName(name_);
        setUrlPath(urlPath_);
        setType(type_);
        setSize(size_);
        resetTouchedOnNotNull();
    }
}
