/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.tables.Media;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.media.created_at_</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media.created_at_</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.media.updated_at_</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media.updated_at_</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.media.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.media.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.media.ref_id_</code>.
     */
    public void setRefId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.media.ref_id_</code>.
     */
    public Long getRefId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.media.ref_type_</code>.
     */
    public void setRefType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.media.ref_type_</code>.
     */
    public String getRefType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.media.file_id_</code>.
     */
    public void setFileId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.media.file_id_</code>.
     */
    public Long getFileId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(Long id_, OffsetDateTime createdAt_, OffsetDateTime updatedAt_, Boolean removed_, Long refId_, String refType_, Long fileId_) {
        super(Media.MEDIA);

        setId(id_);
        setCreatedAt(createdAt_);
        setUpdatedAt(updatedAt_);
        setRemoved(removed_);
        setRefId(refId_);
        setRefType(refType_);
        setFileId(fileId_);
        resetTouchedOnNotNull();
    }
}
