/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.tables.RoomTypeFacilities;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomTypeFacilityRecord extends UpdatableRecordImpl<RoomTypeFacilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.room_type_facilities.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.room_type_facilities.created_at_</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.created_at_</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.room_type_facilities.updated_at_</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.updated_at_</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.room_type_facilities.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.room_type_facilities.room_type_id_</code>.
     */
    public void setRoomTypeId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.room_type_id_</code>.
     */
    public Long getRoomTypeId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.room_type_facilities.facility_id_</code>.
     */
    public void setFacilityId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.room_type_facilities.facility_id_</code>.
     */
    public Long getFacilityId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomTypeFacilityRecord
     */
    public RoomTypeFacilityRecord() {
        super(RoomTypeFacilities.ROOM_TYPE_FACILITIES);
    }

    /**
     * Create a detached, initialised RoomTypeFacilityRecord
     */
    public RoomTypeFacilityRecord(Long id_, OffsetDateTime createdAt_, OffsetDateTime updatedAt_, Boolean removed_, Long roomTypeId_, Long facilityId_) {
        super(RoomTypeFacilities.ROOM_TYPE_FACILITIES);

        setId(id_);
        setCreatedAt(createdAt_);
        setUpdatedAt(updatedAt_);
        setRemoved(removed_);
        setRoomTypeId(roomTypeId_);
        setFacilityId(facilityId_);
        resetTouchedOnNotNull();
    }
}
