/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.tables.Sessions;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionRecord extends UpdatableRecordImpl<SessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sessions.token</code>.
     */
    public void setToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sessions.token</code>.
     */
    public String getToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.sessions.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sessions.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sessions.created</code>.
     */
    public void setCreated(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sessions.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.sessions.expires</code>.
     */
    public void setExpires(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sessions.expires</code>.
     */
    public OffsetDateTime getExpires() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRecord
     */
    public SessionRecord() {
        super(Sessions.SESSIONS);
    }

    /**
     * Create a detached, initialised SessionRecord
     */
    public SessionRecord(String token, Long userId, OffsetDateTime created, OffsetDateTime expires) {
        super(Sessions.SESSIONS);

        setToken(token);
        setUserId(userId);
        setCreated(created);
        setExpires(expires);
        resetTouchedOnNotNull();
    }
}
