/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables.records;


import java.time.OffsetDateTime;

import org.booking_hotel.jooq.model.enums.UserRole;
import org.booking_hotel.jooq.model.tables.Users;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id_</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id_</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.created_at_</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.created_at_</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.users.updated_at_</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.updated_at_</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.users.removed_</code>.
     */
    public void setRemoved(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.removed_</code>.
     */
    public Boolean getRemoved() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.users.first_name_</code>.
     */
    public void setFirstName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.first_name_</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.last_name_</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.last_name_</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.email_</code>.
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.email_</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.password_hash_</code>.
     */
    public void setPasswordHash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.password_hash_</code>.
     */
    public String getPasswordHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.role_</code>.
     */
    public void setRole(UserRole value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.role_</code>.
     */
    public UserRole getRole() {
        return (UserRole) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id_, OffsetDateTime createdAt_, OffsetDateTime updatedAt_, Boolean removed_, String firstName_, String lastName_, String email_, String passwordHash_, UserRole role_) {
        super(Users.USERS);

        setId(id_);
        setCreatedAt(createdAt_);
        setUpdatedAt(updatedAt_);
        setRemoved(removed_);
        setFirstName(firstName_);
        setLastName(lastName_);
        setEmail(email_);
        setPasswordHash(passwordHash_);
        setRole(role_);
        resetTouchedOnNotNull();
    }
}
