/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FacilityTypes = 'main' | 'specific';

export const FacilityTypes = {

    main: 'main' as FacilityTypes,

    specific: 'specific' as FacilityTypes
};

