/**
 * main-app API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {FacilityTypes} from './facility-types';


export interface FacilitySaveResponse {
    id: number;
    name: string;
    iconRef: string;
    type?: FacilityTypes;
}
export namespace FacilitySaveResponse {
}


