/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileSaveResponse { 
    id: number;
    name: string;
    urlPath: string;
    type: string;
    size: number;
}

