/**
 * main-app API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RoomTypeModel} from './room-type-model';


export interface HotelDetailModel {
    id: number;
    name: string;
    address: string;
    phone: string;
    cityId?: number;
    roomTypes?: Array<RoomTypeModel>;
    createdAt: string;
    updatedAt: string;
    removed: boolean;
}

