/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HotelModel { 
    id: number;
    name: string;
    address: string;
    phone: string;
    cityId?: number;
    createdAt: string;
    updatedAt: string;
    removed: boolean;
}

