/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderSaveResponse { 
    id: number;
    fromDate: string;
    toData: string;
    hotelId: number;
    userId: number;
    roomTypeId: number;
}

