/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './user-role';


export interface UserSession { 
    token: string;
    created: string;
    expires: string;
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    role: UserRole;
}
export namespace UserSession {
}


