/**
 * main-app API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'admin' | 'user';

export const UserRole = {

    admin: 'admin' as UserRole,

    user: 'user' as UserRole
};

