export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bed-type.service';
import { BedTypeService } from './bed-type.service';
export * from './city.service';
import { CityService } from './city.service';
export * from './country.service';
import { CountryService } from './country.service';
export * from './facility.service';
import { FacilityService } from './facility.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './hotel.service';
import { HotelService } from './hotel.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './room-type.service';
import { RoomTypeService } from './room-type.service';
export * from './room-type-facility.service';
import { RoomTypeFacilityService } from './room-type-facility.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, BedTypeService, CityService, CountryService, FacilityService, FileService, HotelService, MediaService, OrderService, RoomTypeService, RoomTypeFacilityService, UserService];
