export * from './auth.service';
import {AuthService} from './auth.service';
import {BedTypeService} from './bed-type.service';
import {CityService} from './city.service';
import {CountryService} from './country.service';
import {FacilityService} from './facility.service';
import {FileService} from './file.service';
import {HotelService} from './hotel.service';
import {MediaService} from './media.service';
import {OrderService} from './order.service';
import {RoomTypeService} from './room-type.service';
import {RoomTypeFacilityService} from './room-type-facility.service';
import {UserService} from './user.service';

export * from './bed-type.service';
export * from './city.service';
export * from './country.service';
export * from './facility.service';
export * from './file.service';
export * from './hotel.service';
export * from './media.service';
export * from './order.service';
export * from './room-type.service';
export * from './room-type-facility.service';
export * from './user.service';
export const APIS = [AuthService, BedTypeService, CityService, CountryService, FacilityService, FileService, HotelService, MediaService, OrderService, RoomTypeService, RoomTypeFacilityService, UserService];
