/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables;


import java.time.OffsetDateTime;
import java.util.Collection;

import org.booking_hotel.jooq.model.Keys;
import org.booking_hotel.jooq.model.Public;
import org.booking_hotel.jooq.model.tables.records.RoomTypeRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomTypes extends TableImpl<RoomTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.room_types</code>
     */
    public static final RoomTypes ROOM_TYPES = new RoomTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomTypeRecord> getRecordType() {
        return RoomTypeRecord.class;
    }

    /**
     * The column <code>public.room_types.id_</code>.
     */
    public final TableField<RoomTypeRecord, Long> ID = createField(DSL.name("id_"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.room_types.created_at_</code>.
     */
    public final TableField<RoomTypeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.room_types.updated_at_</code>.
     */
    public final TableField<RoomTypeRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.room_types.removed_</code>.
     */
    public final TableField<RoomTypeRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.room_types.hotel_id_</code>.
     */
    public final TableField<RoomTypeRecord, Long> HOTEL_ID = createField(DSL.name("hotel_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.room_types.bed_type_id_</code>.
     */
    public final TableField<RoomTypeRecord, Long> BED_TYPE_ID = createField(DSL.name("bed_type_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.room_types.name_</code>.
     */
    public final TableField<RoomTypeRecord, String> NAME = createField(DSL.name("name_"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.room_types.count_</code>.
     */
    public final TableField<RoomTypeRecord, Integer> COUNT = createField(DSL.name("count_"), SQLDataType.INTEGER.nullable(false), this, "");

    private RoomTypes(Name alias, Table<RoomTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoomTypes(Name alias, Table<RoomTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.room_types</code> table reference
     */
    public RoomTypes(String alias) {
        this(DSL.name(alias), ROOM_TYPES);
    }

    /**
     * Create an aliased <code>public.room_types</code> table reference
     */
    public RoomTypes(Name alias) {
        this(alias, ROOM_TYPES);
    }

    /**
     * Create a <code>public.room_types</code> table reference
     */
    public RoomTypes() {
        this(DSL.name("room_types"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RoomTypeRecord, Long> getIdentity() {
        return (Identity<RoomTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomTypeRecord> getPrimaryKey() {
        return Keys.ROOM_TYPES_PKEY;
    }

    @Override
    public RoomTypes as(String alias) {
        return new RoomTypes(DSL.name(alias), this);
    }

    @Override
    public RoomTypes as(Name alias) {
        return new RoomTypes(alias, this);
    }

    @Override
    public RoomTypes as(Table<?> alias) {
        return new RoomTypes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypes rename(String name) {
        return new RoomTypes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypes rename(Name name) {
        return new RoomTypes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypes rename(Table<?> name) {
        return new RoomTypes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes where(Condition condition) {
        return new RoomTypes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
