/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.tables;


import java.time.OffsetDateTime;
import java.util.Collection;

import org.booking_hotel.jooq.model.Keys;
import org.booking_hotel.jooq.model.Public;
import org.booking_hotel.jooq.model.tables.records.RoomTypeFacilityRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomTypeFacilities extends TableImpl<RoomTypeFacilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.room_type_facilities</code>
     */
    public static final RoomTypeFacilities ROOM_TYPE_FACILITIES = new RoomTypeFacilities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomTypeFacilityRecord> getRecordType() {
        return RoomTypeFacilityRecord.class;
    }

    /**
     * The column <code>public.room_type_facilities.id_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, Long> ID = createField(DSL.name("id_"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.room_type_facilities.created_at_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.room_type_facilities.updated_at_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at_"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.room_type_facilities.removed_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, Boolean> REMOVED = createField(DSL.name("removed_"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.room_type_facilities.room_type_id_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, Long> ROOM_TYPE_ID = createField(DSL.name("room_type_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.room_type_facilities.facility_id_</code>.
     */
    public final TableField<RoomTypeFacilityRecord, Long> FACILITY_ID = createField(DSL.name("facility_id_"), SQLDataType.BIGINT.nullable(false), this, "");

    private RoomTypeFacilities(Name alias, Table<RoomTypeFacilityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoomTypeFacilities(Name alias, Table<RoomTypeFacilityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.room_type_facilities</code> table
     * reference
     */
    public RoomTypeFacilities(String alias) {
        this(DSL.name(alias), ROOM_TYPE_FACILITIES);
    }

    /**
     * Create an aliased <code>public.room_type_facilities</code> table
     * reference
     */
    public RoomTypeFacilities(Name alias) {
        this(alias, ROOM_TYPE_FACILITIES);
    }

    /**
     * Create a <code>public.room_type_facilities</code> table reference
     */
    public RoomTypeFacilities() {
        this(DSL.name("room_type_facilities"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RoomTypeFacilityRecord, Long> getIdentity() {
        return (Identity<RoomTypeFacilityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoomTypeFacilityRecord> getPrimaryKey() {
        return Keys.ROOM_TYPE_FACILITIES_PKEY;
    }

    @Override
    public RoomTypeFacilities as(String alias) {
        return new RoomTypeFacilities(DSL.name(alias), this);
    }

    @Override
    public RoomTypeFacilities as(Name alias) {
        return new RoomTypeFacilities(alias, this);
    }

    @Override
    public RoomTypeFacilities as(Table<?> alias) {
        return new RoomTypeFacilities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypeFacilities rename(String name) {
        return new RoomTypeFacilities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypeFacilities rename(Name name) {
        return new RoomTypeFacilities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomTypeFacilities rename(Table<?> name) {
        return new RoomTypeFacilities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities where(Condition condition) {
        return new RoomTypeFacilities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypeFacilities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypeFacilities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypeFacilities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomTypeFacilities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomTypeFacilities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
