/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model.enums;


import org.booking_hotel.jooq.model.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum FacilityTypes implements EnumType {

    main("main"),

    specific("specific");

    private final String literal;

    private FacilityTypes(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "facility_types";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static FacilityTypes lookupLiteral(String literal) {
        return EnumType.lookupLiteral(FacilityTypes.class, literal);
    }
}
