/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model;


import java.util.Arrays;
import java.util.List;

import org.booking_hotel.jooq.model.tables.BedTypes;
import org.booking_hotel.jooq.model.tables.Cities;
import org.booking_hotel.jooq.model.tables.Countries;
import org.booking_hotel.jooq.model.tables.Facilities;
import org.booking_hotel.jooq.model.tables.Files;
import org.booking_hotel.jooq.model.tables.FlywaySchemaHistory;
import org.booking_hotel.jooq.model.tables.Hotels;
import org.booking_hotel.jooq.model.tables.Media;
import org.booking_hotel.jooq.model.tables.Orders;
import org.booking_hotel.jooq.model.tables.RoomTypeFacilities;
import org.booking_hotel.jooq.model.tables.RoomTypes;
import org.booking_hotel.jooq.model.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bed_types</code>.
     */
    public final BedTypes BED_TYPES = BedTypes.BED_TYPES;

    /**
     * The table <code>public.cities</code>.
     */
    public final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>public.facilities</code>.
     */
    public final Facilities FACILITIES = Facilities.FACILITIES;

    /**
     * The table <code>public.files</code>.
     */
    public final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.hotels</code>.
     */
    public final Hotels HOTELS = Hotels.HOTELS;

    /**
     * The table <code>public.media</code>.
     */
    public final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.room_type_facilities</code>.
     */
    public final RoomTypeFacilities ROOM_TYPE_FACILITIES = RoomTypeFacilities.ROOM_TYPE_FACILITIES;

    /**
     * The table <code>public.room_types</code>.
     */
    public final RoomTypes ROOM_TYPES = RoomTypes.ROOM_TYPES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BedTypes.BED_TYPES,
            Cities.CITIES,
            Countries.COUNTRIES,
            Facilities.FACILITIES,
            Files.FILES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Hotels.HOTELS,
            Media.MEDIA,
            Orders.ORDERS,
            RoomTypeFacilities.ROOM_TYPE_FACILITIES,
            RoomTypes.ROOM_TYPES,
            Users.USERS
        );
    }
}
