/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model;


import org.booking_hotel.jooq.model.tables.BedTypes;
import org.booking_hotel.jooq.model.tables.Cities;
import org.booking_hotel.jooq.model.tables.Countries;
import org.booking_hotel.jooq.model.tables.Facilities;
import org.booking_hotel.jooq.model.tables.Files;
import org.booking_hotel.jooq.model.tables.FlywaySchemaHistory;
import org.booking_hotel.jooq.model.tables.Hotels;
import org.booking_hotel.jooq.model.tables.Media;
import org.booking_hotel.jooq.model.tables.Orders;
import org.booking_hotel.jooq.model.tables.PgpArmorHeaders;
import org.booking_hotel.jooq.model.tables.RoomTypeFacilities;
import org.booking_hotel.jooq.model.tables.RoomTypes;
import org.booking_hotel.jooq.model.tables.Sessions;
import org.booking_hotel.jooq.model.tables.Users;
import org.booking_hotel.jooq.model.tables.records.PgpArmorHeaderRecord;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.bed_types</code>.
     */
    public static final BedTypes BED_TYPES = BedTypes.BED_TYPES;

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>public.facilities</code>.
     */
    public static final Facilities FACILITIES = Facilities.FACILITIES;

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.hotels</code>.
     */
    public static final Hotels HOTELS = Hotels.HOTELS;

    /**
     * The table <code>public.media</code>.
     */
    public static final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public static final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeaderRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(org.booking_hotel.jooq.model.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return org.booking_hotel.jooq.model.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return org.booking_hotel.jooq.model.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.room_type_facilities</code>.
     */
    public static final RoomTypeFacilities ROOM_TYPE_FACILITIES = RoomTypeFacilities.ROOM_TYPE_FACILITIES;

    /**
     * The table <code>public.room_types</code>.
     */
    public static final RoomTypes ROOM_TYPES = RoomTypes.ROOM_TYPES;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
