/*
 * This file is generated by jOOQ.
 */
package org.booking_hotel.jooq.model;


import org.booking_hotel.jooq.model.tables.Cities;
import org.booking_hotel.jooq.model.tables.Countries;
import org.booking_hotel.jooq.model.tables.Files;
import org.booking_hotel.jooq.model.tables.FlywaySchemaHistory;
import org.booking_hotel.jooq.model.tables.Hotels;
import org.booking_hotel.jooq.model.tables.Media;
import org.booking_hotel.jooq.model.tables.Orders;
import org.booking_hotel.jooq.model.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.hotels</code>.
     */
    public static final Hotels HOTELS = Hotels.HOTELS;

    /**
     * The table <code>public.media</code>.
     */
    public static final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
